### DISCUSSION TITLE
Docker compose not starting with password authentication failed

### DISCUSSION THREAD

**Discussion by Pytonballoon810** [manyfold3d/manyfold#3950] [Support]
**Describe the bug**
I tried using docker compose with this setup:

```yaml
services:
  manyfold:
    container_name: manyfold
    image: ghcr.io/manyfold3d/manyfold:latest
    ports:
      - 3214:3214
    volumes:
      # Uncomment to add a filesystem volume for your model library (or multiple if
      # you want multiple libraries), in the form <local_path>:<container_path>.
      # The local path could be a folder that already contains models, in which case Manyfold
      # will scan and import them, or it could be empty.
      # The container path can be anything; you will need to enter it in the "new library" form.
      - /mnt/3dmodels:/models
    environment:
      DATABASE_ADAPTER: postgresql # mysql2 or sqlite3 are also supported
      DATABASE_HOST: postgres-server
      DATABASE_PORT: 5432 # only needed for non-standard ports
      DATABASE_NAME: manyfold # or the path to the database file if using sqlite3
      DATABASE_USER: manyfold
      DATABASE_PASSWORD: password
      SECRET_KEY_BASE: ZUhRGBqN97CaeJW6d2af93duSPqzdWMc
      REDIS_URL: redis://redis-server:6379/1
      PUID: 1023
      PGID: 1025
      # For details of other optional environment variables, including features such
      # as multiuser mode, visit https://manyfold.app/sysadmin/configuration.html
    restart: unless-stopped
    depends_on:
      - postgres-server
      - redis-server
    networks:
      - manyfold
      # - casa_network
    # Optional, but recommended for better security
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID

  postgres-server:
    container_name: postgres-server
    image: postgres:15
    volumes:
      - /home/manyfold/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: manyfold
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    networks:
      - manyfold

  redis-server:
    container_name: redis-server
    image: redis:7
    restart: unless-stopped
    networks:
      - manyfold

networks:
  manyfold:
  casa_network:
    external: true

```

**Additional context**
The PUID and PGID are from a dedicated manyfold user on the host machine. The Casa network is not used for now since i thaught maybe that was the problem.
Do the password of the postgres-server and the manyfold DATABASE_PASSWORD have to be the same?
i also edded container_name as i thaught maybe the REDIS_URL was the problem.

LOGS:
```logs
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/data_migrate-11.3.0/tasks/databases.rake:153:in 'block (3 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'block in Rake::Task#execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'Array#each'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'Rake::Task#execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:219:in 'block in Rake::Task#invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:199:in 'Monitor#synchronize'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:188:in 'Rake::Task#invoke'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:188:in 'Rake::Application#invoke_task'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'block (2 levels) in Rake::Application#top_level'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'Array#each'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'block in Rake::Application#top_level'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:147:in 'Rake::Application#run_with_threads'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:132:in 'Rake::Application#top_level'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:27:in 'block (2 levels) in Rails::Command::RakeCommand.perform'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:214:in 'Rake::Application#standard_exception_handling'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:27:in 'block in Rails::Command::RakeCommand.perform'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:44:in 'block in Rails::Command::RakeCommand.with_rake'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in 'Rake.with_application'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:41:in 'Rails::Command::RakeCommand.with_rake'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:20:in 'Rails::Command::RakeCommand.perform'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/command.rb:156:in 'Rails::Command.invoke_rake'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/command.rb:73:in 'block in Rails::Command.invoke'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/command.rb:149:in 'Rails::Command.with_argv'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/command.rb:69:in 'Rails::Command.invoke'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands.rb:18:in '<main>'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
Caused by:
PG::ConnectionBad: connection to server at "172.20.0.2", port 5432 failed: FATAL:  password authentication failed for user "manyfold" (PG::ConnectionBad)
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/pg-1.5.9/lib/pg/connection.rb:709:in 'PG::Connection#async_connect_or_reset'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/pg-1.5.9/lib/pg/connection.rb:844:in 'PG::Connection.connect_to_hosts'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/pg-1.5.9/lib/pg/connection.rb:772:in 'PG::Connection.new'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/pg-1.5.9/lib/pg.rb:63:in 'PG.connect'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:58:in 'ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.new_client'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:982:in 'ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#connect'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:994:in 'ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#reconnect'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:662:in 'block in ActiveRecord::ConnectionAdapters::AbstractAdapter#reconnect!'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activesupport-7.2.2.1/lib/active_support/concurrency/null_lock.rb:9:in 'ActiveSupport::Concurrency::NullLock#synchronize'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:661:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#reconnect!'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:763:in 'block in ActiveRecord::ConnectionAdapters::AbstractAdapter#verify!'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activesupport-7.2.2.1/lib/active_support/concurrency/null_lock.rb:9:in 'ActiveSupport::Concurrency::NullLock#synchronize'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:754:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#verify!'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:771:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#connect!'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:977:in 'block in ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activesupport-7.2.2.1/lib/active_support/concurrency/null_lock.rb:9:in 'ActiveSupport::Concurrency::NullLock#synchronize'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:976:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in 'block in ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements#raw_execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activesupport-7.2.2.1/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:1119:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#log'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in 'ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements#raw_execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:538:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#internal_execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:137:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:27:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in 'ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements#execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:46:in 'ActiveRecord::ConnectionAdapters::PostgreSQL::SchemaStatements#create_database'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:23:in 'ActiveRecord::Tasks::PostgreSQLDatabaseTasks#create'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/database_tasks.rb:117:in 'ActiveRecord::Tasks::DatabaseTasks#create'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/data_migrate-11.3.0/lib/data_migrate/database_tasks.rb:231:in 'block (2 levels) in DataMigrate::DatabaseTasks.prepare_all_with_data'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/database_tasks.rb:565:in 'ActiveRecord::Tasks::DatabaseTasks#with_temporary_pool'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/data_migrate-11.3.0/lib/data_migrate/database_tasks.rb:228:in 'block in DataMigrate::DatabaseTasks.prepare_all_with_data'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/database_tasks.rb:606:in 'block (2 levels) in ActiveRecord::Tasks::DatabaseTasks#each_current_configuration'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/database_tasks.rb:603:in 'Array#each'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/database_tasks.rb:603:in 'block in ActiveRecord::Tasks::DatabaseTasks#each_current_configuration'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/database_tasks.rb:614:in 'Array#each'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/database_tasks.rb:614:in 'ActiveRecord::Tasks::DatabaseTasks#each_current_environment'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/tasks/database_tasks.rb:602:in 'ActiveRecord::Tasks::DatabaseTasks#each_current_configuration'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/data_migrate-11.3.0/lib/data_migrate/database_tasks.rb:225:in 'DataMigrate::DatabaseTasks.prepare_all_with_data'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/data_migrate-11.3.0/tasks/databases.rake:153:in 'block (3 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'block in Rake::Task#execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'Array#each'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'Rake::Task#execute'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:219:in 'block in Rake::Task#invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:199:in 'Monitor#synchronize'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:188:in 'Rake::Task#invoke'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:188:in 'Rake::Application#invoke_task'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'block (2 levels) in Rake::Application#top_level'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'Array#each'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'block in Rake::Application#top_level'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:147:in 'Rake::Application#run_with_threads'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:132:in 'Rake::Application#top_level'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:27:in 'block (2 levels) in Rails::Command::RakeCommand.perform'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:214:in 'Rake::Application#standard_exception_handling'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:27:in 'block in Rails::Command::RakeCommand.perform'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:44:in 'block in Rails::Command::RakeCommand.with_rake'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in 'Rake.with_application'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:41:in 'Rails::Command::RakeCommand.with_rake'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands/rake/rake_command.rb:20:in 'Rails::Command::RakeCommand.perform'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/command.rb:156:in 'Rails::Command.invoke_rake'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/command.rb:73:in 'block in Rails::Command.invoke'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/command.rb:149:in 'Rails::Command.with_argv'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/command.rb:69:in 'Rails::Command.invoke'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/railties-7.2.2.1/lib/rails/commands.rb:18:in '<main>'
/usr/src/app/vendor/bundle/ruby/3.4.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
Tasks: TOP => db:prepare:with_data
(See full trace by running task with --trace)
2025-04-07T13:29:40.088Z pid=3056 tid=2w INFO: Sidekiq 7.3.9 connecting to Redis with options {size: 10, pool_name: "internal", url: "redis://redis-server:6379/1"}
WARNING: table: "settings" does not exist or not database connection, `SiteSettings.anonymous_usage_id` fallback to returns the default value.
Preparing database...

```
