### ISSUE TITLE
TrueNAS CORE plugin

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1697]
NLNet 5.3

**Comment by Floppy** [comment]
TrueNAS have released new custom docker image support recently, so this might be much more doable than before.

**Comment by Nealtron** [comment]
As mentioned, now that TrueNAS SCALE uses standard Docker, it was pretty easy to deploy via docker-compose. 

I successfully deployed Manyfold on TrueNAS Scale 24.10 using the example docker-compose file. I ultimately made minor modifications to the docker-compose file based on my own preferences. 

```
networks:
  manyfold: Null
services:
  app:
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: postgres
      DATABASE_NAME: manyfold
      DATABASE_PASSWORD: examplepassword
      DATABASE_PORT: 5432
      DATABASE_USER: manyfold
      PGID: 1000
      PUID: 1000
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: examplesecretkey
    image: ghcr.io/manyfold3d/manyfold:latest
    links:
      - postgres
      - redis
    networks:
      - manyfold
    ports:
      - '3214:3214'
    volumes:
      - libraries:/libraries
  postgres:
    environment:
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_USER: manyfold
    image: postgres:15
    networks:
      - manyfold
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    networks:
      - manyfold
    restart: on-failure
version: '3'
volumes:
  db_data:
    driver_opts:
      device: /mnt/Pool01/Apps01/manyfold01/database
      o: bind
      type: none
  libraries:
    driver_opts:
      device: /mnt/Pool01/Apps01/manyfold01/libraries/
      o: bind
      type: none
```
