### ISSUE TITLE
Infinite redirects in single user mode

### ISSUE THREAD

**Issue by staceybellerose** [manyfold3d/manyfold#2147]
**Describe the bug**
When in single user mode, if you have not yet logged in with the browser, a redirect (HTTP 302) loop between `/` and `/users/sign_in` occurs. The easiest way to see this is using curl.

**To Reproduce**
1. `curl -D - -L http://main-manyfold-url`
2. See edited curl log below for error

```
$ curl -D - -L http://main-manyfold-url
HTTP/2 302 
date: Tue, 07 May 2024 09:14:29 GMT
content-type: text/html; charset=utf-8
location: https://main-manyfold-url/users/sign_in
cache-control: no-cache
set-cookie: <snip>
x-runtime: 0.037455
cf-cache-status: DYNAMIC
report-to: <snip>
server: cloudflare
cf-ray: 8800199bbfd86a1d-MCI
alt-svc: h3=":443"; ma=86400

HTTP/2 302 
date: Tue, 07 May 2024 09:14:29 GMT
content-type: text/html; charset=utf-8
location: https://main-manyfold-url/
cache-control: no-cache
content-language: en
referrer-policy: strict-origin-when-cross-origin
set-cookie:  <snip>
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: 92848d34-50e0-4571-910f-7f25ca34f33e
x-runtime: 0.028549
x-xss-protection: 0
cf-cache-status: DYNAMIC
report-to: <snip>
server: cloudflare
cf-ray: 8800199c28546a1d-MCI
alt-svc: h3=":443"; ma=86400

HTTP/2 302 
date: Tue, 07 May 2024 09:14:29 GMT
content-type: text/html; charset=utf-8
location: https://main-manyfold-url/users/sign_in
cache-control: no-cache
set-cookie: <snip>
x-request-id: 911d97dd-635d-42c8-90e7-853e15b5f9d0
x-runtime: 0.010452
cf-cache-status: DYNAMIC
report-to: <snip>
server: cloudflare
cf-ray: 8800199c788e6a1d-MCI
alt-svc: h3=":443"; ma=86400

HTTP/2 302 
date: Tue, 07 May 2024 09:14:29 GMT
content-type: text/html; charset=utf-8
location: https://main-manyfold-url/
cache-control: no-cache
content-language: en
referrer-policy: strict-origin-when-cross-origin
set-cookie: <snip>
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: 15baf06a-c99d-45f6-9471-feee35180a4a
x-runtime: 0.023633
x-xss-protection: 0
cf-cache-status: DYNAMIC
report-to: <snip>
server: cloudflare
cf-ray: 8800199ca8cb6a1d-MCI
alt-svc: h3=":443"; ma=86400

<snip more redirects>

curl: (47) Maximum (50) redirects followed
```

**Expected behavior**
An HTML page is returned.

**Additional context**
- Manyfold Version: 0.65.0 (992508e)
- Running in Docker container using `docker compose`:

```
services:
  app:
    image: ghcr.io/manyfold3d/manyfold
    ports:
      - 3214:3214
    volumes:
      - ./libraries:/libraries
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_BASE}?pool=5
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: redis://redis:6379/1
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - vandam
    links:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - vandam
  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - vandam
    volumes:
      - redis-data:/data
networks:
  vandam:
volumes:
  redis-data:
  pg-data:
```

I noticed this when upgrading to the latest version of Manyfold and my server monitor failed with a "too many redirects" error. To temporarily resolve the issue, I enabled multi-user mode and disable registrations.
