### ISSUE TITLE
Check file/folder permissions and raise problems if wrong

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#2505]

**Comment by PhilipWhiteside** [comment]
For whoever finds this next. The owner:group is set by the envs PUID/PGID defaulting to `1000:1000`.

I was using a docker volume for my libraries instead of a folder.

```yaml
nas ➜  manyfold cat docker-compose.yml 
services:
  app:
    image: ghcr.io/manyfold3d/manyfold:latest
    ports:
      - 3214:3214
    volumes:
      - libraries:/libraries
    environment:
      PUID: 1000
      PGID: 1000
...
volumes:
  db_data:
  libraries:
...
```
```sh
nas ➜  manyfold docker volume ls | grep manyfold
local     manyfold_db_data
local     manyfold_libraries
```

Default service name is `app`
```sh
nas ➜  manyfold docker compose ps
NAME                         IMAGE                                COMMAND                  SERVICE           CREATED          STATUS          PORTS
manyfold-app-1               ghcr.io/manyfold3d/manyfold:latest   "/init"                  app               42 minutes ago   Up 42 minutes   0.0.0.0:3214->3214/tcp, :::3214->3214/tcp
manyfold-postgres-server-1   postgres:15                          "docker-entrypoint.s…"   postgres-server   42 minutes ago   Up 42 minutes   5432/tcp
manyfold-redis-server-1      redis:7                              "docker-entrypoint.s…"   redis-server      42 minutes ago   Up 42 minutes   6379/tcp

```

My library folder is called `default`
```sh
nas ➜  manyfold docker compose exec -it app mkdir /libraries/default
nas ➜  manyfold docker compose exec -it app ls -lah /libraries/               
total 16K    
drwxr-xr-x    4 root     root        4.0K Sep  1 15:18 .
drwxr-xr-x    1 root     root        4.0K Sep  1 14:40 ..
drwxr-xr-x    2 root     root        4.0K Sep  1 15:18 default
nas ➜  manyfold docker compose exec -it app chown 1000:1000 /libraries/default
nas ➜  manyfold docker compose exec -it app ls -lah /libraries/                
total 16K    
drwxr-xr-x    4 root     root        4.0K Sep  1 15:18 .
drwxr-xr-x    1 root     root        4.0K Sep  1 14:40 ..
drwxr-xr-x    2 1000     1000        4.0K Sep  1 15:18 default
nas ➜  manyfold 
```
