### ISSUE TITLE
Issues when trying to deploy using MYSQL external DB: non-standard port config issues, notable delay in preparing DB, various mysql2 errors

### ISSUE THREAD

**Issue by NeoMod** [manyfold3d/manyfold#3138]
**Describe the bug**

When trying to deploy the "latest" image on docker, using external REDIS and MySQL DB running on custom port, the initialization fails with a "Connection Error" from Mysql2.

Reading the logs, it would appear that the container is expecting the MySQL DB container to be always available on standard port (TCP:3306). I tried using the variable "DATABASE_PORT" to specify a different port but to no avail.

Using the DATABASE_URL variable, providing full connection string, I was able to establish a connection on a different port, but then other problems emerged:

- I had to add the "SYS_ADMIN" cap to resolve the issue about /run not mounted as tmpfs at container start (I'm not sure if this issue is specific to UNRAID);
- I had to add the picutils package inside the image to resolve the "lspci error";

Then I noticed an unusual delay between the start of the container and the start of DB preparing phase: the container "waited" for about 8/10 minutes before starting the operations on DB after first creating tables. (not sure if this is relevant) A lot of notice/error messages filled the logs, afterward, along the lines of:

```
::Error: BLOB, TEXT, GEOMETRY or JSON column 'pagination_settings' can't have a default value (Mysql2::Error)
(........)
0617122809 AddPaginationSettingsToUser: migrating ======================
-- add_column(:users, :pagination_settings, :json, {:default=>{"models"=>true, "creators"=>true, "collections"=>true, "per_page"=>12}})
Preparing database...
/usr/src/app/vendor/bundle/ruby/3.3.0/gems/opengl-bindings-1.6.14/lib/opengl.rb:1: warning: /usr/local/lib/ruby/3.3.0/fiddle.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add fiddle to your Gemfile or gemspec to silence this warning.
Also please contact the author of opengl-bindings-1.6.14 to request adding fiddle into its gemspec.
Illegal option -p
sh: lspci: not found
Illegal option -p
sh: lspci: not found
/usr/src/app/config/initializers/openssl.rb:6: warning: already initialized constant OpenSSL::SSL::SSLContext::DEFAULT_PARAMS
/usr/local/lib/ruby/3.3.0/openssl/ssl.rb:24: warning: previous definition of DEFAULT_PARAMS was here
/usr/src/app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34: warning: /usr/local/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of devise_zxcvbn-6.0.0 to request adding ostruct into its gemspec.
2024-11-11T20:24:17.183Z pid=3483 tid=4qb INFO: Sidekiq 7.3.5 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://172.18.0.43:6379/0"}
2024-11-11T20:24:17.201Z pid=3483 tid=4qb INFO: Cron Jobs - added job with name: clear-shrine-cache
WARNING: table: "settings" does not exist or not database connection, `SiteSettings.anonymous_usage_id` fallback to returns the default value.
bin/rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)
```

I let the container run for 30 minutes or so, and it seems this "pagination_settings" error is another loop.

Just to exclude any issues with my machine, I tried running the "solo" image tag and it worked as expected, although with a few warnings inside the log.

**To Reproduce**

Deploy the docker image using a pre-existing database (MySQL) container and a pre-existing Redis container like so:

```
services:
  manyfold:
    image: ghcr.io/manyfold3d/manyfold:latest
    container_name: manyfold
    ports:
      - 3214:3214
    volumes:
      - /mnt/user/dati/libreria3D:/libraries
    environment:
      DATABASE_ADAPTER: mysql2 
      DATABASE_URL: mysql2://manyfold:DB-PASSWORD@172.18.0.2:DB_PORT/manyfold
      SECRET_KEY_BASE: some-long-random-key
      REDIS_URL: redis://172.18.0.43:6379/0
      PUID: 99 #specific to UNRAID
      PGID: 100 #specific to UNRAID
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - SYS_ADMIN #need to add this to fix tmpfs issue

    networks:
        neobridge:
            ipv4_address: 172.18.0.45

networks:
  neobridge:
    external: true
```

**Expected behavior**

Service initialization completing without errors, webservice starting on dedicated port. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: UNRAID 6.12.13
 - Browser: Vivaldi
 - Version: 7.0.3495.11 (Stable channel)
