### ISSUE TITLE
Previews not visible behind cloudflare proxying

### ISSUE THREAD

**Issue by DarrenF-G** [manyfold3d/manyfold#448]
Hi guys,

I'm having an issue where the stl previews don't seem to be rendering correctly, they just show as a grey box as seen below.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/42316329/160797079-60d7d403-97c8-492c-806c-47077fdc2059.png">

I can download the files fine and the .png file preview seems to work. the files inside the container are root:root 775.
Sometimes when i move from page to page i will see the stl files render for a split second but them disappear again. could it be maybe something different about my stl files thats causing the renderer to crash? they are all exported from tinkercad if that makes any different? here's an example stl
[wyse_bottom.stl.zip](https://github.com/Floppy/van_dam/files/8379139/wyse_bottom.stl.zip)

checked the /logs URL but don't see any specific errors that stand out
[logs.zip](https://github.com/Floppy/van_dam/files/8379232/logs.zip)

running from the latest container image on ubuntu 20.04.03 lts, 5.4.0
docker ver 20.10.2:2291f61

my compose
```
version: "3"
services:
  app:
    image: ghcr.io/floppy/van_dam:latest
    container_name: 3dp
    ports:
      - 3214:3214
    volumes:
      - "/var/lib/docker/containers/3dp/libraries:/libraries"
    environment:
      DATABASE_URL: postgresql://username:password@172.16.1.76/van_dam?pool=5
      SECRET_KEY_BASE: 
      GRID_SIZE: 260
    depends_on:
      - db
      - redis

    networks:
      new-macvlan-network:
        ipv4_address: 172.16.1.75

  db:
    image: postgres:13
    container_name: 3dp_postgres
    volumes:
       - "/var/lib/docker/containers/3dp-db/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    restart: always
    networks:
      new-macvlan-network:
        ipv4_address: 172.16.1.76

  redis:
    image: redis:6
    container_name: 3dp_redis
    restart: on-failure
    networks:
      new-macvlan-network:
        ipv4_address: 172.16.1.77

volumes:
  3dp_db_data:
networks:
  new-macvlan-network:
    external:
      name: new-macvlan-network
```

Any other logs I can look at to help narrow down the issue? or things to test out?
Thanks.
